create table scan_metadata (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles,
  scan_id text,
  created_at timestamp with time zone default now()
);

alter table scan_metadata
  enable row level security;

create policy "Users can view their own scan metadata." on scan_metadata
  for select using (auth.uid() = user_id);

create policy "Users can insert their own scan metadata." on scan_metadata
  for insert with check (auth.uid() = user_id);
